name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config

      - name: Debug Kubernetes Connection
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods --all-namespaces

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml
          kubectl apply -f cluster-issuer.yaml
          kubectl apply -f certificate.yaml
        shell: /usr/bin/bash -e {0}
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
