name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Debug Kubernetes Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml --validate=false
